### ISSUE TITLE
Provide Security Minded Implementation Guidance? (XCOLD Info Leak)

### ISSUE THREAD

**Issue by kingthorin** [ccampbell/chromelogger#63]
@ccampbell 

Hi Craig, just wanted to point you to some research:
- http://zaproxy.blogspot.ca/2016/01/zap-newsletter-2016-january.html#Feature
- http://files.meetup.com/12990252/XCOLD-OWASP-Ottawa-20160125.pdf

Which leads to the suggestion that your wiki/readme.md etc have some guidance on implementation considerations and security, such as:
1. Do you want this turned on for Production use? (Maybe only test/dev/staging/uat? Can you control it's enable state via a web app/server config file?)
2. If you do want it on for Production use can you ensure that  you don’t leak information that might be leveraged by an attacker or malicious individual?
3. Can you tie it to your authorization framework so that the information (header + content) is returned only to admins and support personnel not “all” users?

"You" in the above numbered items refers to the System Owner/Dev/SysAdmin.

**Comment by ccampbell** [comment]
@kingthorin thanks for reaching out and for showing the research. Clearly many people are misusing this tool!

I thought it would be common sense to not use it in production or send sensitive data, but clearly I am mistaken.

I will be sure to add some security notes to the website/readme files some time soon

**Comment by ccampbell** [comment]
Sorry for the long delay, but I added some information to the main page here: https://craig.is/writing/chrome-logger#security

**Comment by kingthorin** [comment]
@ccampbell looks good
