### ISSUE TITLE
headers already sent...

### ISSUE THREAD

**Issue by bitkahuna** [ccampbell/chromelogger#65]
added include (php) for class definition to code (wordpress theme functions.php file) that executes before any output.
added test output line to a template (footer.php) file:
<?php ChromePhp::log('Hello console!'); ?>

and i get an error:
Warning: Cannot modify header information - headers already sent by (output started at /xxxxxxxx/header.php:3) in /xxxxxxxxxxx/ChromePhp.php on line 394

**Comment by ccampbell** [comment]
This is because you can’t send headers after the output of the page has already been started. See this post for more information (and workaround):

http://stackoverflow.com/questions/9959597/setting-up-chromephp-for-wordpress-using-xampp
