### ISSUE TITLE
chromelogger for Classic ASP (VbScript) 

### ISSUE THREAD

**Issue by danielmarcoto** [ccampbell/chromelogger#66]
I created a library for using with Classic ASP (VbScript). It's been useful to me, and I think it could be useful to any ASP dev. So, here is the project: https://github.com/danielmarcoto/asp2console
If you have any comment or suggestion, please let me know.

**Comment by ccampbell** [comment]
Thanks @danielmarcoto! I added a link to the README and the chromelogger.com site
